### ISSUE TITLE
Failed to load ressources (css/js)

### ISSUE THREAD

**Issue by FelixBuehler** [UB-Mannheim/eScriptorium_Dokumentation#5]
Hey everybody,

I tried to install eScriptorium, but the final step somehow fails partially. The server starts fine and is running. but some/all? assets aren't loaded.
After the command `python manage.py runserver --settings escriptorium.local_settings` it also show this error message, maybe that's connected with it?
```
WARNINGS:
?: (staticfiles.W004) The directory '/home/felix/escriptorium/app/../front/dist' in the STATICFILES_DIRS setting does not exist.
```

Also it is not quite clear for me, why i need a new terminal for the `DJANGO_SETTINGS_MODULE` command? In step 19 this isn't mentioned again. It also leads to errors because of the wrong path/venv(?).

Website:
![image](https://github.com/user-attachments/assets/793d6abc-3a2e-4856-b955-8b9d13f58884)

Developer console:
![image](https://github.com/user-attachments/assets/dba04e63-6a30-40c1-a8b5-aeec3c0ede23)

**Comment by FelixBuehler** [comment]
This happens on both Windows 10 x64 with WSL and with Ubuntu 24.04.1 LTS (with the adapted code from the other bug report).

**Comment by stweil** [comment]
Please run all steps in the same terminal. It looks like you missed [step 10](https://github.com/UB-Mannheim/eScriptorium_Dokumentation/blob/main/Lokale_Installation_eScriptorium.md#10-produktive-nutzung) which creates /home/felix/escriptorium/front/dist.

**Comment by stweil** [comment]
So it did not run without error. Maybe you have a broken installation. I suggest to run `git status`.

**Comment by FelixBuehler** [comment]
I'd like to point out, that the error appears on two different computers with different systems (Ubuntu24 and Windows 10 WSL)
So maybe something in the files/manual is wrong?


git status:

```
On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   app/locale/de/LC_MESSAGES/django.mo
        modified:   app/locale/de/LC_MESSAGES/django.po
        modified:   app/locale/fr/LC_MESSAGES/django.mo
        modified:   app/locale/fr/LC_MESSAGES/django.po
        modified:   app/locale/nb/LC_MESSAGES/django.po

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        app/locale/en/LC_MESSAGES/django.mo
        app/locale/en/LC_MESSAGES/django.po
        app/locale/nb/LC_MESSAGES/django.mo
        package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by stweil** [comment]
There should not be a package-lock.json. Its existence shows that `npm run production` was run from the wrong directory.

**Comment by FelixBuehler** [comment]
From which folder should the `npm run production` have been called? I just copy/paste everything in the manual.
According to that, the working directory is still in `front` when calling it.

**Comment by stweil** [comment]
`/home/felix/escriptorium/front` is correct (and uses the existing package-lock.json), but obviously it was called from `/home/felix/escriptorium`.

**Comment by FelixBuehler** [comment]
Started anew, made sure the path is right, same error:

```
(env) felix@Felix-PC:~/escriptorium/front$ npm run production

> escriptorium@0.1.0 production
> webpack --config webpack.prod.js

assets by status 11.1 MiB [cached] 45 assets
orphan modules 1.49 MiB [orphan] 1077 modules
runtime modules 6.7 KiB 33 modules
code generated modules 8.62 MiB (javascript) 470 KiB (css/mini-extract) [code generated]
  built modules 8.62 MiB [built] 203 modules
  css modules 470 KiB
    modules by path ./vue/components/ 93.1 KiB 66 modules
    modules by path ./node_modules/ 321 KiB 11 modules
    modules by path ./vue/pages/ 17.7 KiB 6 modules
    modules by path ./css/*.css 26.8 KiB
      css ./node_modules/css-loader/dist/cjs.js!./css/escriptorium.css 25 KiB [code generated]
      + 2 modules
    css ./node_modules/css-loader/dist/cjs.js!./vue/index.css 12.2 KiB [code generated]

ERROR in ./src/editor/main.js + 514 modules
Unexpected end of JSON input

ERROR in ./vue/exports/documentDashboard.js + 409 modules
Unexpected end of JSON input

ERROR in ./vue/exports/imagesPage.js + 416 modules
Unexpected end of JSON input

3 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.91.0 compiled with 3 errors in 26625 ms
```

**Comment by stweil** [comment]
Which Linux distribution did you run in WSL? I'll try to reproduce your installation steps.

**Comment by FelixBuehler** [comment]
Ubuntu 22.04.5 LTS
But the same is happening on a standalone Ubuntu 24.04.1 LTS.

**Comment by stweil** [comment]
Citing the instructions: "Die folgende Installationsanleitung basiert auf einer Installation unter Linux mit den Linux-Distributionen Ubuntu 20.04.3 oder Debian 11."

**Comment by stweil** [comment]
> Ubuntu 22.04.5 LTS But the same is happening on a standalone Ubuntu 24.04.1 LTS.

Ubuntu [Ubuntu noble (24.04LTS)](https://packages.ubuntu.com/noble/python3) comes with Python 3.12 which still cannot be used with eScriptorium.

**Comment by FelixBuehler** [comment]
So i tried VirtualBox with Ubuntu 20.04.6 and that works.
WSL with Ubuntu 22.04 LTS keeps failing for me. How did you try it? Standalone or WSL?

I think WSL is the problem. I'm also not able to do the `npm audit fix`, it just gets this far and then does nothing else (no reappering console):
```
(env) felix@Felix-PC:~/escriptorium/front$ npm audit fix
(node:5842) ExperimentalWarning: CommonJS module /usr/local/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/local/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
⠴
```

On the VirtualBox Ubuntu 20 the `npm audit fix` did work and after that the installation went through.

Are you able to also test it on a WSL?

**Comment by stweil** [comment]
It's notmal that `npm audit fix` takes some time, so maybe you just have to wait a little longer. And it is also an optional step which tries to fix some security issues by installing newer packages. This is not relevant for a local installation without internet connection. So you can simply proceed on WSL if it really does not work.

**Comment by stweil** [comment]
Additional note: I changed the instructions for the npm commands, but see in your protocol that you still used the old instructions which installed npm in /usr/local.

**Comment by FelixBuehler** [comment]
So after completely purging node and npm from the system, it finally worked. Had to do these:
Thanks for the help so far!
Small hint: You also removed the instruction, to press Enter after the celery worker started. I would add this again, since it's quite confusing, that after sending the prompt, the shell appears at first, then the celery worker takes over, but never goes back to the prompt when not pressing enter, which is quite uncommon.

```
sudo apt-get remove nodejs npm node
sudo apt-get purge nodejs

sudo rm -rf /usr/local/bin/npm 
sudo rm -rf /usr/local/share/man/man1/node* 
sudo rm -rf /usr/local/lib/dtrace/node.d 
sudo rm -rf ~/.npm 
sudo rm -rf ~/.node-gyp 
sudo rm -rf /opt/local/bin/node 
sudo rm -rf opt/local/include/node 
sudo rm -rf /opt/local/lib/node_modules  
sudo rm -rf /usr/local/lib/node*
sudo rm -rf /usr/local/include/node*
sudo rm -rf /usr/local/bin/node*
```

**Comment by stweil** [comment]
The prompt is there, but overwritten by the log messages from the celery workers. So pressig <enter> is not required, but optional. I am also not sure whether everybody who reads a German documentation knows which key is the <enter> key. Only the full keyboard on my office pc has a key which is labeled so in the numeric keypad. That's why I removed this part of the documentation.
